config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, without: :destroy, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: [:index, :show]
  resources :friendships, only: [:create, :destroy] do 
  	member { get :accept }
  end
  resources :posts, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: :create
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :posts, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :likeable, source_type: "Post"
  
  has_many :comments, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  validates :name, presence: true

  before_save :remove_whitespace_in_name
  
  after_create :send_welcome_email

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.email = auth.info.email
  		user.password = Devise.friendly_token[0,20]
  		user.name = auth.info.name
  	end
  end

  def friends?(user)
    self.friends.to_a.include?(user)
  end

  def pending_friends
    User.where(id: self.friendships.where(status: :sent).select(:friend_id))
  end

  def friends_to_accept
    User.where(id: self.friendships.where(status: :received).select(:friend_id))
  end

  def accepted_friends
    User.where(id: self.friendships.where(status: :accepted).select(:friend_id))
  end

  def likes?(likeable)
    self.likes.where(likeable: likeable).exists?
  end

  def feed
    Post.where(user_id: self.accepted_friends.pluck(:id) << self.id )
  end

  
  private
    def remove_whitespace_in_name
      self.name = self.name.strip.gsub(/\s+/, " ")
    end

    def send_welcome_email
      UserMailer.welcome(self).deliver
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
	
	def index
		@users = User.paginate(page: params[:page])
		store_location
	end

	def show
		@user = User.find(params[:id])
		@friends = @user.accepted_friends.paginate(page: params[:page])
		@posts = @user.posts.paginate(page: params[:page])
		store_location
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.slim
#user_index
	h2 Users
	- @users.each do |user|
		.user
			= link_to user.name, user
			- unless current_user == user 
				- if current_user.pending_friends.include?(user) 
					= render 'friendships/cancel', friend_id: user.id 
				- elsif current_user.friends_to_accept.include?(user) 
					= render 'friendships/accept', friend_id: user.id 
				- elsif current_user.accepted_friends.include?(user) 
					= render 'friendships/unfriend', friend_id: user.id 
				- else 
					= render 'friendships/add_friend', friend_id: user.id 
	= will_paginate @users 

app/views/users/show.slim
- provide(:title, @user.name)

h2 = @user.name
- unless current_user = @user
	- if current_user.friends?(@user)
		= link_to 'Unfriend', friendship_path(friend_id: @user.id), method: :delete
	- else
		= link_to 'Add Friend', friendships_path(friend_id: @user.id), method: :post

- unless @posts.empty?
	.posts
		h3 Posts
		- @posts.each_with_index do |post, index|
			= render post, index: index
	= will_paginate @posts

- unless @friends.empty?
	h3 Friends
	- @friends.each do |friend| 
		p = link_to(friend.name, user_path(friend))
	= will_paginate @friends