config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, without: :destroy, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users, only: [:index, :show]
  resources :friendships, only: [:create, :destroy] do 
  	member { get :accept }
  end
  resources :posts, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: :create
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user

	has_many :likes, as: :likeable, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user

	has_many :comments, dependent: :destroy
	
	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 10000 }

	default_scope -> { order('created_at DESC') }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!
	
	def create
		@post = current_user.posts.build(post_params)
		flash[:error] = "Couldn't create post.  It is either blank or too long." unless @post.save
		redirect_back_or_default
	end
	
	def destroy
		@post = current_user.posts.find_by(id: params[:id])
		if @post
			@post.destroy
			redirect_back_or_default
		else
			flash[:error] = "Post couldn't be destroyed"
			redirect_back_or_default
		end
	end

	private
		def post_params
			params.require(:post).permit(:content)
		end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.slim
div class="post" id="post_#{index}"
	= render 'shared/link_to_author_and_time', authored_item: post
	p = post.content
	- if current_user == post.user
		p = link_to "Remove post", post_path(post.id), method: :delete
	- unless post.likes.empty?
		p = pluralize(post.likes.count, 'like')
	- unless post.user == current_user
		p = render 'shared/like_or_unlike', likeable: post
	- unless post.comments.empty?
		h4 Comments
		- post.comments.each do |comment|
			.comment
				= render 'shared/link_to_author_and_time', authored_item: comment
				p = comment.content
	= render 'comments/comment_form', post: post

app/views/posts/_post_form.slim
#create_post
h3 Create Post
= form_for post do |f|
	= render 'shared/error_messages', object: f.object
	= f.text_area :content
	= f.submit "Submit post"